# GoMCP Framework Configuration File
# This file defines agents, registries, servers, and tools using simple YAML syntax

# API Key for authentication (also checks AGENTCONFIG env variable)

agents:
  - agent_id: "weather_agent"
    description: "Weather specialist agent"
    llm:
      api_key: 
      model: "claude-sonnet-4-5-20250929"
      temperature: 0.2
      max_tokens: 555
    servers:
      - "C:/Users/antho/GoMCP/serverconfigs/server1config.yaml"